### ISSUE TITLE
Fix jenkins CSP configuration

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-qe#11]
Hello @iocanel ,

can you please fix jenkins CSP configuration [1] ?
It breaks e2e test reports visualisation. 
See [2] - you can't expand ui entries to see what failed.

[1] https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-e2e-tests/view/change-requests/job/PR-1/6/artifact/e2e/cucumber-reports/cucumber-report.html#collapseFeature2

[2] https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-e2e-tests/view/change-requests/job/PR-1/6/artifact/e2e/cucumber-reports/cucumber-report.html

**Comment by iocanel** [comment]
You will have to give me more than that, as I don't understand what is broken, neither how "csp" affects it.

**Comment by jludvice** [comment]
* during the `yarn e2e` I generate `cucumber-report.html` file.
* This file is archived by jenkins
* the html file has
    * embedded images
    * links to some javascript

Jenkins is blocking loading of those images and javascript files.

This is what I get from jenkins now:
![screenshot_20170713_121939](https://user-images.githubusercontent.com/8707241/28161911-9c5690a2-67c5-11e7-9fb1-2ebafb6ed29c.png)

This is what I want to get:
![screenshot_20170713_122137](https://user-images.githubusercontent.com/8707241/28162000-e67daf62-67c5-11e7-9926-2e5a11ab00a5.png)

**Comment by iocanel** [comment]
From @dsimansk this is realted to: https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by rhuss** [comment]
Anything which can be done for this task ? I'm asking because we might want to close the parent epic, too.

**Comment by dsimansk** [comment]
This issue is outdated and not needed anymore, closing.
