### ISSUE TITLE
Create scenario to cover DB connector

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#114]
From @KurtStam 

> Covering:
> the new sql-stored-start connector - to start of an integration with a stored procedure
> the new CRUD DB connector

**Comment by rhuss** [comment]
@dsimansk Do you already have input for that ? I'm just eagerly searching for such a scenario ...

**Comment by KurtStam** [comment]
So far we have this: https://github.com/syndesisio/syndesis/issues/403

**Comment by dsimansk** [comment]
The majority was done in the linked PRs. Closing this task and details can be addressed separately.
