### ISSUE TITLE
Create variant of CI job that can be pointed to any running instance of Syndesis

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#130]
Use current CI job as a template and apply following changes:

- [x] add new ConfigMap with valid credentials for production cluster
- [x] add parameters: URL, scenario, secret-name
- [x] extend former `e2e-xvfb.sh` script to reflect scenario param
- [x] remove initialization of new Syndesis instance (`Prepare stage`)
- [x] remove clean-up (`Clean-up stage`)

**Comment by dsimansk** [comment]
I've a feeling all subtasks are done. Wdyt @mcada can we close it?

**Comment by mcada** [comment]
Sure thing, closing.
