### ISSUE TITLE
Multi browser support for Protractor tests

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#158]
Create configuration that will enable switching browser on demand. Lets settle witch Chrome and Firefox for now. But lets research also Edge and its requirements <-- @mcada

**Comment by mcada** [comment]
[Done with this PR.](https://github.com/syndesisio/syndesis-qe/pull/157)
Edge can be implemented but we have to set up edge driver. We will consider adding this option into java testsuite. 
[Here you can also check experimental multicapabilities set up to run both browsers at the same time.](https://github.com/mcada/syndesis-qe/commit/2ae505a99694567a381da3bc8fa02d4c8267572e)

This issue may be closed @dsimansk ?

**Comment by dsimansk** [comment]
Sure this is closable...
