### ISSUE TITLE
Connection tests clean-up and additions

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#159]
Currently there're 3 feature files that refers to some variant of CRUD operation on Connections. Please merge those 3 to comprehensive feature file with various scenarios. Make sure to follow common naming pattern etc.

Plus add tests to cover form validation during Connection creation process with all possible outcomes.

**Comment by dsimansk** [comment]
@mcada I believe this was done. Can you pls link your PR and close?

**Comment by mcada** [comment]
done with PR#166, closing
