### ISSUE TITLE
Salesforce connector actions tests

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#204]
Currently we have the following actions available through SF's connector. Lets track in this issue progress on coverage all of them. 

@kcbabo can you pls confirm this is a list of SF actions we want to proceed with?

- [ ] Create or update record
- [ ] Delete record
- [ ] Delete record by external identifier
- [ ] Fetch record
- [ ] Fetch record by external identifier
- [ ] New record
- [x] On create
- [x] On delete
- [x] On update
- [ ] Update record

NOTE: when picking up an action to address, pls create a separate issue to indicate `in progress` work for others and add comment here.

**Comment by kcbabo** [comment]
Looks good to me.  Would be good for @dhirajsb and @zregvart to review as well.

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
