### ISSUE TITLE
Refactor getElementContainingText method to target the search

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#214]
I'd like to be able to be more specific about where to look for and what to return. 

For example I want to get `integration-item` element from list. When I would use `getText()` on such an element the result would have name && status as a one string. 

Therefor I suggest that we introduce parent and text location element to be used if needed. 

@lvydra @Stefan365 wdyt?

```java
public SelenideElement getElementContainingText(By by, String text) {
		ElementsCollection elements = getRootElement().findAll(by).shouldBe(sizeGreaterThan(0));
		log.info("I found " + elements.size() + " elements.");

		elements = elements.filter(exactText(text));
		log.info("Elements after filter: " + elements.size());
		SelenideElement element = elements.shouldBe(sizeGreaterThan(0)).first();
		return element;
	}
```

**Comment by Stefan365** [comment]
@dsimansk why not..

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
