### ISSUE TITLE
Tune up the structure and the class names in Java testsuite

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis-qe#217]
I have found the current java testsuite being not as easy understandable for newbies as it could/should be.
I have changed **connections** part of the suite so far... it is not fully functional. It's only a prototype.
What do you think about that? @Stefan365 @lvydra @mmelko @dsimansk 

The commit description:
    [java testsuite] Connections - new class structure skeleton proposal
    

- proposing class structure and naming that follows physical UI structure and page names reflecting headlines or other significant labels

- experimental
  - removing Page and Component suffixes. It should be clear from file structure or.. it is simply not needed.
  - class names are shorter and more readable
  - component/page status can be added to the class description if somebody need it...or we can create Page and Component interfaces...

The changes can be found [here](https://github.com/mastepan/syndesis-qe/tree/rename-connections/ui-tests/src/test/java/io/syndesis/qe/pages/connections).

**Comment by dsimansk** [comment]
See the [comparison](https://github.com/syndesisio/syndesis-qe/compare/master...mastepan:rename-connections) with current master.

**Comment by Stefan365** [comment]
@mastepan 
IMO, 
I would keep Page/Component suffixes, just for the same reason of higher readability. 
My argument is distinguish them by the first look from auxiliary / 'not to page related' classes.
The rest you mention (following headlines, etc. could be of use), is good idea, but we were using similar approach: names of classes based on names of elements and that I find slightly better.

For 'wizard' as I understood it (some general term that fit both edit/create) I have nothing against. 
I also had idea to unify create/edit under one term. They are almost unified(edit), only exception is ConnectionCreatePage(create), but then, after discussion I kept this exception.

**Comment by mastepan** [comment]
@Stefan365 

> My argument is distinguish them by the first look from auxiliary / 'not to page related' classes.

Can you find any example? Perhaps...It may be more obvious when renaming Integrations area...I can't see any troubles so far. We can use more descriptive variable names but I would avoid it either if possible. Shorter names are more readable in general if they contain all necessary information.

> The rest you mention (following headlines, etc. could be of use), is good idea, but we were using similar approach: names of classes based on names of elements and that I find slightly better.

Do you mean the tags in the source code or what names of elements? We need to discuss and compare the examples. The names you use now can be result of the current code design... I would like to discover what is the cause of such names.

We ought to discuss this in the office. And put here the result of what we will have agreed on.

**Comment by lvydra** [comment]
@mastepan @Stefan365 My opinion is somewhere in the middle. Please let me know if you plan some office discussion.

**Comment by Stefan365** [comment]
@mastepan 👍 for discussion topic in the office

**Comment by dsimansk** [comment]
Closing this one, this was rejected if I remember correctly :)
