### ISSUE TITLE
Test Performance Impact of DB based Logging

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-qe#276]
PR https://github.com/syndesisio/syndesis/pull/1054 implements DB based integration log capture and a simple UI for it.  I uses that same underlying DB table that the rest of syndesis uses to store it's logging information.  There is concern that logging to the same table could impact the UI responsiveness of the rest of the application.

Please create tests to measure the UI responsiveness as we increase the logging load placed on the system.  Perhaps create an integration that produces moderate logging load by perhaps executing an integration once per second.  Run that and check to see what some of the UI response times are.
Then continue running additional integrations that add more logging load.  

At what point does the UI become unresponsive?  Please run these tests on the ignite cluster where we have real hardware.

**Comment by dsimansk** [comment]
@chirino 
I've captured load times from browser console for Integrations and Connections pages on the Ignite cluster. There's best and worst numbers from 10 iterations. The average is to load ~1.5s and the whole finish ~2.40s. It seems there's no significant trend to downgrade the performance when the logs are being captured into DB. 

The integration was Periodic SQL invoke -> Stored procedure, that in fact uses the same DB also.

```
//No running integration
Integrations (full load): Finish: 2.24s | DOMContentLoaded: 1.50 s | Load: 1.50 s
                                       Finish: 2.32s | DOMContentLoaded: 1.56 s | Load: 1.56 s
Connections (full load):  Finish: 2.190s | DOMContentLoaded: 1.43 s | Load: 1.43 s
                                         Finish: 2.490s | DOMContentLoaded: 1.65 s | Load: 1.65 s

//One running integration with 1s logging period
Integrations (full load): Finish: 2.43s | DOMContentLoaded: 1.49 s | Load: 1.49 s
                                       Finish: 2.54s | DOMContentLoaded: 1.72 s | Load: 1.72 s
Connections (full load):  Finish: 2.28s | DOMContentLoaded: 1.49 s | Load: 1.49 s
                                        Finish: 2.39s | DOMContentLoaded: 1.57 s | Load: 1.57 s

```

**Comment by dsimansk** [comment]
@chirino wha SQL qeury should I use to check if the logs are really stored into DB, just to be sure?

**Comment by chirino** [comment]
@dsimansk 'GET /api/v1/logs/{integrationId}'
That should get you the log data we are tracking.

It would be good to find out what the breaking point it is.  By either running multiple integrations or increasing the frequency of exchanges run.

**Comment by dsimansk** [comment]
I've increased message rate to 100ms on 1 integration.

OoM: I've noticed few OoMs when `jsondb` was filled after ~1h. There was ~250K rows at the time. I'm not entirely sure if it's a problem of too many rows in total, or too many rows being fetched at once after a period of inactivity. Anyway reaching that 200K+ rows in DB seems to introduce more instability over time. When the integration is running the `syndesis-rest` is balancing on 600-610 MB memory consumption (current limit in cluster is set for 612).

**Comment by chirino** [comment]
Ok. I need to attach a memory profiler to see what's holding on to the memory. Thx for the heads up.

**Comment by dsimansk** [comment]
@chirino I've moved this issue to next sprint. Since the original PR is merged. Is there anything else I could help with evaluating the performance issues && memory footprint?

**Comment by chirino** [comment]
Could you send me a stack trace to get an idea of the number of threads running and what they are doing.  I'v noticed a large number of XNIO threads when I've tested, perhpas on your env it's even larger and something we need to tune better.

The other thing is figuring out how to get heap dump out.

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
