### ISSUE TITLE
Investigate API connector updates

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#289]
There're new features/options coming from https://github.com/syndesisio/syndesis/issues/183 lets include them to our tests.

**Comment by mastepan** [comment]
https://github.com/syndesisio/syndesis/issues/803

**Comment by dsimansk** [comment]
@mastepan a bit more comments and context would be appreciated.

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
