### ISSUE TITLE
Add prettier to enforce code formatting across IDEs

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#31]

**Comment by rhuss** [comment]
@dsimansk can this issue be closed as the associated PR has been merged ?

**Comment by dsimansk** [comment]
@rhuss Well, I wanted to keep in the backlog and revisit once again in future. It's not a priority and we couldn't agree if we actually like the enforced code format due to line-breaking of method's params etc.

**Comment by dsimansk** [comment]
This is something we won't need anymore.
