### ISSUE TITLE
Investigate Upgrade features

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#318]
Related materials:
- Epic with substasks: 
  - Infra upgrade: https://github.com/syndesisio/syndesis/issues/1117
  - Runtime upgrade: https://github.com/syndesisio/syndesis/issues/1118
- Feature proposal: https://github.com/syndesisio/syndesis/blob/master/project/proposals/971-upgrade.adoc
- Bash script: https://github.com/syndesisio/syndesis/blob/master/tools/bin/commands/upgrade

**Comment by tplevko** [comment]
Closing, upgrade scenario automated: https://github.com/syndesisio/syndesis-qe/pull/446
