### ISSUE TITLE
Disable Delete button on API Connector list page if uses != 0

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis-qe#347]

**Comment by mastepan** [comment]
https://github.com/syndesisio/syndesis/issues/847

**Comment by mastepan** [comment]
May be blocked by https://github.com/syndesisio/syndesis/issues/1827#issuecomment-371045716

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
