### ISSUE TITLE
Review gherkin steps naming

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis-qe#371]

**Comment by mastepan** [comment]
tasks:

- review using the/a
...more will come

**Comment by dsimansk** [comment]
Few more thoughts:

- remove user reference completely from step definition
  - substitute with one step that will be able to log in provided user (when needed)
- imperative step definition
- review repetitive steps that could be wrapped in a meta step similar to `create connection`
  - goal is to reduce verbosity of partial steps (but they're still important to target specific UI behaviour)
- review usage of DataTables
  - more of DT, less or actually optimal usage


... to be continued...

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
