### ISSUE TITLE
Test data mapper seperate feature

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-qe#38]
Verify that 1 input field and be separated and mapped into 2 output fields based on a user selected separator character.  

This should be tested E2E from configuring in the mapper UI to running an actual integration and validating the feature is working as expected.  Edge cases should be explored.  Like when input does not match what would normally be expected.

**Comment by dsimansk** [comment]
@Stefan365 can you pls take a look at separate and extend the existing code from combine to have also separate available https://github.com/syndesisio/syndesis-qe/issues/148
