### ISSUE TITLE
Test data mapper combine feature 

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-qe#39]
Verify that 2 input fields can be combined into 1 output field based using a user selected separator character.  

This should be tested E2E from configuring in the mapper UI to running an actual integration and validating the feature is working as expected.  Edge cases should be explored.  Like when input does not match what would normally be expected.

**Comment by dsimansk** [comment]
This was done via https://github.com/syndesisio/syndesis-qe/issues/148.
