### ISSUE TITLE
Refactor integrations

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis-qe#393]
- files/folders structure, split IntegrationSteps

**Comment by mastepan** [comment]
- files/folders structure, split IntegrationSteps

**Comment by mastepan** [comment]
Idea - what about to modify breadcrumbs to have 
Home > Integrations > New Integration > **Choose Connection** > Choose Action
Its weird you can't go back to connection selection.
Isn't there an issue for that already @mcada ?

**Comment by mcada** [comment]
Yes, issue was put into backlog :(
https://github.com/syndesisio/syndesis/issues/317

**Comment by dsimansk** [comment]
Done
