### ISSUE TITLE
Export/import integration between two syndesis instances

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis-qe#467]
reaction to: https://github.com/syndesisio/syndesis/issues/2585

Tracking issue. Create test when fixed.

**Comment by mcada** [comment]
Test is ready, but it contains workaround due to mentioned issue. This  should stay tracked and after syndesis#2585 issue is fixed test should be updated accordingly.

**Comment by tplevko** [comment]
I'm closing this now, we will update the tests when the issue get's fixed. We will be notified and we can react then.
