### ISSUE TITLE
Investigate Oracle DB usability in e2e tests

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis-qe#474]
Investigate possibility of using dballocator with our tests. If it's feasible, create a simple integration scenario which would use Oracle DB.

**Comment by Stefan365** [comment]
one note, library: org.jboss.qa.dballoc.dballocator-client-rest cannot be used due to conflict in: resteasy-jaxrs version.
After discussion with @tplevko I'll do DB allocation via HTTP requests.

**Comment by avano** [comment]
Closing all GH issues in syndesis-qe project, if it is still relevant, please open FUSEQE JIRA for that
