### ISSUE TITLE
Obsolete scenarios cleanup

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#79]
For a while now I want to remove [this scenarios](https://github.com/syndesisio/syndesis-e2e-tests/blob/master/e2e/narratives/08-first-pass.feature), as there's no real value in it anymore.

@jludvice @lvydra wdyt? Are there others to drop?

**Comment by jludvice** [comment]
my two cents to cleanup #80

**Comment by dsimansk** [comment]
Done via #80.
