### ISSUE TITLE
Test data mapper using repeating elements

### ISSUE THREAD

**Issue by jpav** [syndesisio/syndesis-qe#82]
Test data mapper e2e for scenarios involving repeating elements:

- Ensure repeating elements can be mapped to other repeating elements
- Ensure appropriate warnings are displayed when invalid sources/targets are selected for mappings involving repeating elements
- Ensure appropriate indexes can be selected when mapping a specific item in a repeating element to another field

Expected output should be tested for along with the user experience.

**Comment by dsimansk** [comment]
Tracked in the linked issue.
