### ISSUE TITLE
Test data mapping auto conversion

### ISSUE THREAD

**Issue by jpav** [syndesisio/syndesis-qe#83]
Test data mapper e2e to ensure mappings for fields of different types are handled appropriately:

- Ensure an appropriate data type conversion is automatically made when possible.  A separate test for each possible conversion type should exist.
- Ensure appropriate warnings are displayed when auto-conversion is not possible.

**Comment by igarashitm** [comment]
This will be succeeded by atlasmap/atlasmap-qe#5
