### ISSUE TITLE
Test data mapper when source is used for multiple targets

### ISSUE THREAD

**Issue by jpav** [syndesisio/syndesis-qe#84]
Test data mapper e2e when a source is mapped to multiple targets:

- Ensure user has ability to select which mapping they want to edit
- Ensure mapping lines connect selected source/target only (assuming the showing all lines "toolbar" button is not selected)
- Ensure user can easily create additional mappings using the same source
- Ensure user can delete specific mapping from source to target without deleting other mapping involving that same source

**Comment by dsimansk** [comment]
Done via https://github.com/atlasmap/atlasmap-qe/pull/18
